apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "t2ps-chatbot.services.proxy.configuration" . }}
  namespace: {{ include "t2ps-chatbot-ui.namespace" . }}
  labels:
    {{- include "t2ps-chatbot-ui.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
data:
  chatbot-services-proxy.conf: |-
    {{- tpl (.Files.Get "files/chatbot-services-proxy.conf") . | nindent 4 }}
