{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "t2ps-chatbot-ui.fullname" . }}
  namespace: {{ include "t2ps-chatbot-ui.namespace" . }}
  labels:
    {{- include "t2ps-chatbot-ui.labels" . | nindent 4 }}
    {{- with .Values.ingress.labels }}
      {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
  {{- with (mergeOverwrite (deepCopy .Values.annotations) .Values.ingress.annotations) }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    {{- with .Values.ingress.hosts }}
      {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
  tls:
    {{- with .Values.ingress.tls }}
      {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
{{- end }}
